# Generated by Django 5.1.1 on 2024-12-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_notificacion_tema_remove_respuesta_tema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='banear_hasta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='aprobado',
        ),
    ]
